In [10]:
import pickle
import pandas as pd

In [8]:
artiles = open('../data/articles_embeddings.pickle','rb')
data = pickle.load(artiles)

In [17]:
data = pd.DataFrame(data)
data['click_article_id'] = data.index

In [18]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,241,242,243,244,245,246,247,248,249,click_article_id
0,-0.161183,-0.957233,-0.137944,0.050855,0.830055,0.901365,-0.335148,-0.559561,-0.500603,0.165183,...,0.313999,0.636412,0.169179,0.540524,-0.813182,0.286870,-0.231686,0.597416,0.409623,0
1,-0.523216,-0.974058,0.738608,0.155234,0.626294,0.485297,-0.715657,-0.897996,-0.359747,0.398246,...,0.823124,0.412688,-0.338654,0.320787,0.588643,-0.594137,0.182828,0.397090,-0.834364,1
2,-0.619619,-0.972960,-0.207360,-0.128861,0.044748,-0.387535,-0.730477,-0.066126,-0.754899,-0.242004,...,0.473184,0.377866,-0.863887,-0.383365,0.137721,-0.810877,-0.447580,0.805932,-0.285284,2
3,-0.740843,-0.975749,0.391698,0.641738,-0.268645,0.191745,-0.825593,-0.710591,-0.040099,-0.110514,...,0.036040,0.480029,-0.763173,0.022627,0.565165,-0.910286,-0.537838,0.243541,-0.885329,3
4,-0.279052,-0.972315,0.685374,0.113056,0.238315,0.271913,-0.568816,0.341194,-0.600554,-0.125644,...,0.809268,0.427521,-0.615932,-0.503697,0.614450,-0.917760,-0.424061,0.185484,-0.580292,4

In [11]:
click = pd.read_csv('../data/click/clicks_hour_000.csv')

In [13]:
df = pd.DataFrame()
df = df.append(click)

In [14]:
df.col

,user_id,session_id,session_start,session_size,click_article_id,click_timestamp,click_environment,click_deviceGroup
0,0,15068254230001,1506825423000,2,157541,1506826828020,4,3
1,0,15068254230001,1506825423000,2,68866,1506826858020,4,3
2,1,15068254260002,1506825426000,2,235840,1506827017951,4,1
3,1,15068254260002,1506825426000,2,96663,1506827047951,4,1
4,2,15068254350003,1506825435000,2,119592,1506827090575,4,1
5,2,15068254350003,1506825435000,2,30970,1506827120575,4,1
6,3,15068254420004,1506825442000,2,236065,1506827536942,4,3
7,3,15068254420004,1506825442000,2,236294,1506827566942,4,3
8,4,15068255280005,1506825528000,2,48915,1506826927593,4,1
9,4,15068255280005,1506825528000,2,44488,1506826957593,4,1
10,5,15068255410006,1506825541000,3,168868,1506826884885,4,1
11,5,15068255410006,1506825541000,3,207122,1506827097562,4,1
12,5,15068255410006,1506825541000,3,286413,1506827127562,4,1
13,6,15068255530007,1506825553000,2,202436,1506826872215,4,3
14,6,15068255530007,1506825553000,2,288431,1506826902215,4,3
15,7,15068255680008,1506825568000,2,235840,1506828125628,4,1
16,7,15068255680008,1506825568000,2,284847,1506828155628,4,1
17,8,15068255730009,1506825573000,3,332114,1506826999683,4,3
18,8,15068255730009,1506825573000,3,284847,1506827438642,4,3
19,8,15068255730009,1506825573000,3,114161,1506827468642,4,3
20,9,150682559900010,1506825599000,2,284346,1506828088734,4,3
21,9,150682559900010,1506825599000,2,285412,1506828118734,4,3
22,10,150682560200011,1506825602000,3,198420,1506826975475,4,1
23,10,150682560200011,1506825602000,3,198322,1506827046578,4,1
24,10,150682560200011,1506825602000,3,202436,1506827076578,4,1
25,11,150682561700012,1506825617000,2,207122,1506827186038,4,3
26,11,150682561700012,1506825617000,2,119592,1506827216038,4,3
27,12,150682561700013,1506825617000,3,288431,1506828524266,4,3
28,12,150682561700013,1506825617000,3,159359,1506828802674,4,3
29,12,150682561700013,1506825617000,3,119592,1506828832674,4,3
...,...,...,...,...,...,...,...,...
2059,752,1506828937000753,1506828937000,2,355863,1506828949119,4,3
2060,752,1506828937000753,1506828937000,2,106819,1506828979119,4,3
2061,753,1506828941000754,1506828941000,5,108854,1506829603019,4,3
2062,753,1506828941000754,1506828941000,5,235840,1506829922283,4,3
2063,753,1506828941000754,1506828941000,5,288431,1506830194566,4,3
2064,753,1506828941000754,1506828941000,5,284847,1506830582293,4,3
2065,753,1506828941000754,1506828941000,5,331293,1506830612293,4,3
2066,754,1506828946000755,1506828946000,2,108854,1506828986579,4,3
2067,754,1506828946000755,1506828946000,2,145166,1506829016579,4,3
2068,755,1506828948000756,1506828948000,3,284847,1506828979505,4,3
2069,755,1506828948000756,1506828948000,3,233671,1506829305565,4,3
2070,755,1506828948000756,1506828948000,3,119592,1506829335565,4,3
2071,756,1506828949000757,1506828949000,2,235840,1506829002312,4,3
2072,756,1506828949000757,1506828949000,2,145166,1506829032312,4,3
2073,757,1506828949000758,1506828949000,2,145166,1506830052928,4,3
2074,757,1506828949000758,1506828949000,2,159359,1506830082928,4,3
2075,758,1506828951000759,1506828951000,2,235840,1506829061037,2,3
2076,758,1506828951000759,1506828951000,2,284847,1506829091037,2,3
2077,759,1506828958000760,1506828958000,2,84094,1506829062893,4,3
2078,759,1506828958000760,1506828958000,2,83472,1506829092893,4,3
2079,760,1506828960000761,1506828960000,5,162245,1506830731898,4,1
2080,760,1506828960000761,1506828960000,5,251735,1506830809579,4,1
2081,760,1506828960000761,1506828960000,5,258386,1506830868850,4,1
2082,760,1506828960000761,1506828960000,5,141517,1506830969954,4,1
2083,760,1506828960000761,1506828960000,5,157541,1506830999954,4,1
2084,761,1506828968000762,1506828968000,2,119592,1506830912301,4,1
2085,761,1506828968000762,1506828968000,2,284847,1506830942301,4,1
2086,762,1506828979000763,1506828979000,3,108854,1506829027334,4,3
2087,762,1506828979000763,1506828979000,3,96663,1506829095732,4,3
2088,762,1506828979000763,1506828979000,3,68866,1506829125732,4,3